### ISSUE TITLE
[doc] swap space size?

### ISSUE THREAD

**Issue by kaizoku-oh** [wolfSSL/wolfBoot#110]
In the document: [Targets.md](https://github.com/wolfSSL/wolfBoot/blob/master/docs/Targets.md) in line 34
Did you mean:

> the swap space must be as big as **128KB**

instead of:

> the swap space must be as big as **64KB**

**Comment by danielinux** [comment]
Hello @kaizoku-oh - Thanks for spotting this! This is now fixed.
