### ISSUE TITLE
Cannot compile IAR example project

### ISSUE THREAD

**Issue by kaizoku-oh** [wolfSSL/wolfBoot#114]
The IAR example project for stm32f4 found under IDE/IAR is not able to compile.
After generating the keypair using the generate_key.bat script I wasn't able to compile the project.
I'm using IAR 8.50.9 on Windows 10 x64.
I feel like I'm missing something?

![SharedScreenshot1](https://user-images.githubusercontent.com/22129291/107048083-6485df00-677d-11eb-906d-bc891c9bcdaa.jpg)
![SharedScreenshot2](https://user-images.githubusercontent.com/22129291/107048095-6780cf80-677d-11eb-8c21-54c07ffd9065.jpg)

**Comment by danielinux** [comment]
Hello @kaizoku-oh,

what is the target platform? You may need to define your partitioning in `include/target.h`. When `make` is used, the file is created automatically. In your case, you may want to create it manually starting from `include/target.h.in`, and specifying the flash geometry.

The `include/target.h` automatically generated when using make, configured for the STM32F407 with the parameters in the documentation is the following:

```
#ifndef H_TARGETS_TARGET_
#define H_TARGETS_TARGET_

#define WOLFBOOT_SECTOR_SIZE                 0x20000
#define WOLFBOOT_PARTITION_BOOT_ADDRESS      0x20000
#define WOLFBOOT_PARTITION_SIZE              0x20000 
#define WOLFBOOT_PARTITION_UPDATE_ADDRESS    0x40000
#define WOLFBOOT_PARTITION_SWAP_ADDRESS      0x60000

#endif /* !H_TARGETS_TARGET_ */
```

**Comment by kaizoku-oh** [comment]
Yes, that is what I was missing, I created an **include/target.h** file and it compiled without errors (although there were some warnings)
Thanks @danielinux
