### ISSUE TITLE
Raspberry Pi 3b hardware memory alignment issue

### ISSUE THREAD

**Issue by nkapu** [wolfSSL/wolfBoot#122]
WolfBoot crashes to alignment fault on unaligned access during sha3 calculation on the Raspberry Pi 3b hardware. Running on QEMU Raspberry Pi 3b mode is ok and no alignment exception occurs. Unaligned access occurs in the Wolfcrypt sha3 implementation (sha3.c) at https://github.com/wolfSSL/wolfssl/blob/0d995527aa76a2333b558fcf259145c2646b4c72/wolfcrypt/src/sha3.c#L557

Apparently  "AArch64 does permit unaligned data accesses to Normal (not Device) memory with the regular load/store instructions." However in the early stages of the boot all memory is treated as device memory (MMU is not enabled), and this is probably how it should be for the bootloader since the actual payload (like Linux kernel) may expect pristine and clean state to start with. Potentally related background on the armv8 behaviour: https://armv8-ref.codingbelief.com/en/chapter_d4/d42_8_the_effects_of_disabling_a_stage_of_address_translation.html

Following gadget will workaround this issue by using xmemcpy instead of 64-bit load/store when access is not aligned on 8-byte boundary:

```
--- a/lib/wolfssl/wolfcrypt/src/sha3.c
+++ b/lib/wolfssl/wolfcrypt/src/sha3.c
@@ -554,7 +554,14 @@ static word64 Load64BitBigEndian(const byte* a)
 
     return n;
 #else
-    return *(word64*)a;
+    word64 ret;
+
+    if ((unsigned long) a % 8) {
+        XMEMCPY(&ret, a, sizeof(word64));
+        return ret;
+    }
+
+    return *(const word64*)a;
````

With that workaround there is a performance hit but no crash and Wolfboot can be used to boot up Linux kernel successfully.

**Comment by dgarske** [comment]
Fixed in https://github.com/wolfSSL/wolfssl/pull/3995
