### ISSUE TITLE
API in README to trigger update

### ISSUE THREAD

**Issue by Hajer97** [wolfSSL/wolfBoot#142]
In wolfBoot's README ( https://github.com/wolfSSL/wolfBoot/blob/master/README.md )
In Upgrading the firmware section, the API to call to trigger a firmware update is wolfBoot_update(), but in wolfboot/wolfboot.h and in the docs the function's name is wolfBoot_update_trigger().

**Comment by elms** [comment]
Thanks @Hajer97. This is related to previous report #136 (PR #137)
