### ISSUE TITLE
Internal flash encryption 

### ISSUE THREAD

**Issue by kaizoku-oh** [wolfSSL/wolfBoot#145]
Is there a way to use firmware encryption in internal flash rather than external?

**Comment by danielinux** [comment]
Not on microcontrollers. The image must be in plain text to be executed in place. Some microcontrollers have a built-in symmetric encryption feature that can be used (e.g. NXP K80 series), where the symmetric key can be set at boot time.

Encryption of external flash memories prevents wiretapping attacks, e.g. on SPI bus assuming that the attacker has physical access to the target.
