### ISSUE TITLE
PIC32MZ HAL

### ISSUE THREAD

**Issue by RevoluPowered** [wolfSSL/wolfBoot#2]
Curious if you are going to be implementing a pre-configured PIC32 HAL target in the future?

I would adopt this boot-loader for our devices if this was the case.
Thanks,
Gordon

**Comment by danielinux** [comment]
Hello Gordon,
The HAL is very simple and it only requires a few (6) functions to be implemented for the specific device. Please see [HAL.md](../tree/master/docs/HAL.md) for details.

Hardware support for a specific platform can be easily implemented, all it takes is actual access to a development board.

You will see more and more platforms supported in the future. Stay tuned.
