### ISSUE TITLE
Uefi shell wolfssl efi

### ISSUE THREAD

**Issue by charge007** [wolfSSL/wolfBoot#237]
### Version

Latest

### Description

Can anyone please point out some use cases for having wolfssl.efi build?
Also, is there any guide for that?

Thanks

**Comment by embhorn** [comment]
Hello @charge007 

I've transferred this issue to the wolfBoot project.

Here is the UEFI example.
https://github.com/wolfSSL/wolfBoot/tree/master/tools/efi

We'll answer any follow up questions in the ZenDesk ticket you created.
