### ISSUE TITLE
Content of keystore.der generated by kengen is not correct

### ISSUE THREAD

**Issue by ydengxue** [wolfSSL/wolfBoot#291]
The following line in the function "_keystore_add_" of tools/keytools/keygen.c does not seem to be correct:
fwrite(**&sl, sl.pubkey_size**, 1, fpub_image);

It should be:
"fwrite(**sl.pubkey, sl.pubkey_size**, 1, fpub_image);" 
or 
"fwrite(**&sl, sizeof(sl)-KEYSLOT_MAX_PUBKEY_SIZE+sl.pubkey_size**, 1, fpub_image);". 
Right?

**Comment by danielinux** [comment]
Hi @ydengxue - Thanks for noticing this. The second case is the correct one, I'm going to commit a fix.

**Comment by danielinux** [comment]
Closed by #292
