### ISSUE TITLE
Write firmware signing/key generator tools in python

### ISSUE THREAD

**Issue by EduardShaid** [wolfSSL/wolfBoot#4]
Is it possible to transfer tools to the language of PYTHON ? That would be very convenient.

**Comment by danielinux** [comment]
I was actually already considering to port the tools to a more portable language. I could definitely look into this. Thanks for the suggestion.

**Comment by danielinux** [comment]
@EduardShaid  thanks again for the suggestion. The tools were rewritten in python to extend the portability.
Check PR #6
