### ISSUE TITLE
KeyGenTool Have Some Problem

### ISSUE THREAD

**Issue by lifeng5478** [wolfSSL/wolfBoot#415]
key_import does not match RSA file import

and RSA2048 KeySize not 320.its 294

![image](https://github.com/wolfSSL/wolfBoot/assets/3992865/c9fc6618-4252-42c4-9659-794941657908)
![image](https://github.com/wolfSSL/wolfBoot/assets/3992865/c89df900-8e39-4104-8bc3-14490a22c219)
and then another thing,,,,uhmmm. maybe not a question。 
![image](https://github.com/wolfSSL/wolfBoot/assets/3992865/0e6c44c6-ac02-4e48-88d0-6534e5933676)
because i do not use the special section to set this keystore.

**Comment by jpbland1** [comment]
Hey @lifeng5478,

Could you share what version of wolfBoot these screenshots are from? It doesn't match what I'm seeing in our keytools, and I know this has been refactored recently. When that key_import code gets called the public key is already loaded into memory and for RSA is already in the correct format to use so it will be a little different from our normal file import procedure.

I'm not sure what you're asking about the keystore, are you saying you don't use keyimport.c for your keystore and have configured something else?

Best Wishes,
John Bland

**Comment by danielinux** [comment]
Hello @lifeng5478 

Did you have time to check @jpbland1 's comments above? Which version of wolfBoot are you running? How are you importing the key from the keystore structure?

**Comment by danielinux** [comment]
Closing due to lack of detailed information. Feel free to reopen if you see the issue again.
