### ISSUE TITLE
Getting delta base version from filename is error prone

### ISSUE THREAD

**Issue by StuartGorman** [wolfSSL/wolfBoot#527]
In file `wolfBoot/tools/keytools/sign.c:1780` the delta base version is extracted from the filename of the image as the first number between "\_v" and the next "\_". However, the delta image creation requires a signed base file, and the image version is contained within the image header. The signing tool should pull the version from the image header, given that the bootloader will use the version from that location when applying the delta.

This will prevent issues where the file is renamed with the version string (for the purpose of artifact management), as opposed to the integer version (in the scenario where the printed text of those version are different).

**Comment by danielinux** [comment]
@StuartGorman thanks for the suggestion. I've made PR #532 to address this.
