### ISSUE TITLE
BOOT, UPDATE, SWAP Partitions

### ISSUE THREAD

**Issue by cui632** [wolfSSL/wolfBoot#9]
Do those partitions have same size ?  the design seems to be pretty secure. but it also takes big flash space to realize.  is there any optimization on it ?

**Comment by danielinux** [comment]
BOOT and UPDATE have indeed the same size. 
SWAP partition must be (at least) as big as the flash physical sector. On many platform the SWAP partition can be 2-4KB.

When flash space is a concern, SWAP and UPDATE partition can be moved to any external memory (e.g. SPI), leaving most of the programming flash avaiilable to use for BOOT.
